spring:
  profiles:
    active: local
    include:
      - cloud
jwt:
  secret-access: culinaryheavenculinaryheavenculinaryheavenculinaryheavenculinaryheaven
  secret-refresh: culinaryheavenculinaryheavenculinaryheavenculinaryheavenculinaryheavenrefresh
  access-token-validity-in-seconds: 1800
  refresh-token-validity-in-seconds: 1296000

logging:
  level:
    org.springframework.boot.context.config: TRACE

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus

firebase:
  private-key-path: classpath:culinary-heaven-firebase-adminsdk.json