spring:
  profiles:
    active: local
    include:
      - cloud
jwt:
  secret-access: culinaryheavenculinaryheavenculinaryheavenculinaryheavenculinaryheaven
  secret-refresh: culinaryheavenculinaryheavenculinaryheavenculinaryheavenculinaryheavenrefresh
  access-token-validity-in-seconds: 1800
  refresh-token-validity-in-seconds: 1296000

